# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='fuck',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
