# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_fuck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='fuck',
        ),
    ]
