# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_users_fuck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('device_type', models.IntegerField()),
                ('last_online', models.DateTimeField(verbose_name='last device online in system')),
            ],
        ),
    ]
