# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Users'),
        ),
    ]
