# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_devices_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='device_type',
        ),
    ]
