# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_devices_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('device_type', models.IntegerField()),
            ],
        ),
    ]
