# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_devicetypes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceTypes',
            new_name='DeviceModels',
        ),
        migrations.AddField(
            model_name='devices',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.DeviceModels'),
        ),
    ]
